import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "About — Jay, Licensed Pharmacist",
  description:
    "ClearRx was built by Jay, a licensed pharmacist and senior pharmaceutical researcher, to give patients clear, honest drug interaction information.",
};

export default function AboutPage() {
  return (
    <article className="max-w-2xl mx-auto px-4 py-16 space-y-8">
      <header>
        <h1 className="font-serif text-4xl">About ClearRx</h1>
        <p className="mt-4 text-base font-sans" style={{ color: "var(--ink-muted)" }}>
          Built by a pharmacist who got tired of watching patients get buried in FDA label copy.
        </p>
      </header>

      <section className="space-y-4 text-base font-sans leading-relaxed" style={{ color: "var(--ink-muted)" }}>
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>Who I Am</h2>
        <p>
          I'm Jay, a licensed pharmacist with over a decade of clinical experience in retail,
          hospital, and research settings. I specialize in pharmacokinetics and drug-drug
          interactions — specifically how the CYP450 enzyme system affects medication safety.
        </p>
        <p>
          I review medication profiles daily. The most common question I get: "Is it safe to
          take these together?" Existing tools either overwhelm patients with clinical jargon
          or bury the answer under three ad units and a pop-up.
        </p>
      </section>

      <section className="space-y-4 text-base font-sans leading-relaxed" style={{ color: "var(--ink-muted)" }}>
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>Why I Built ClearRx</h2>
        <p>
          ClearRx is my answer to that problem. It's a tool I would actually hand to a patient.
          Clean, fast, private. No account. No data sent anywhere. Results in plain English,
          reviewed by a pharmacist — not generated by an algorithm with no accountability.
        </p>
        <p>
          Every interaction explanation on this site was written or reviewed by me. I stand
          behind every word.
        </p>
      </section>

      <div
        className="p-5 border text-sm font-sans"
        style={{ borderColor: "var(--border)", background: "var(--rx-accent-light)" }}
      >
        <p className="font-mono text-xs uppercase mb-2" style={{ color: "var(--rx-accent)" }}>
          Credentials
        </p>
        <ul className="space-y-1 list-disc list-inside" style={{ color: "var(--ink-muted)" }}>
          <li>PharmD — Licensed Pharmacist</li>
          <li>Senior Pharmaceutical Researcher</li>
          <li>Clinical Pharmacokinetics Specialist</li>
          <li>CYP450 Drug Interaction Expert</li>
        </ul>
      </div>
    </article>
  );
}
