import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About — Jay, Licensed Pharmacist",
  description:
    "ClearRx was built by Jay, a licensed pharmacist and senior pharmaceutical researcher with over a decade of clinical experience, to give patients clear, honest drug interaction information.",
};

export default function AboutPage() {
  const personJsonLd = {
    "@context": "https://schema.org",
    "@type": "Person",
    name: "Jay",
    jobTitle: "Licensed Pharmacist",
    description:
      "Licensed pharmacist and senior pharmaceutical researcher specializing in clinical pharmacokinetics and CYP450 drug-drug interactions.",
    knowsAbout: [
      "Drug Interactions",
      "Clinical Pharmacokinetics",
      "CYP450 Enzyme System",
      "Polypharmacy Management",
      "Medication Safety",
    ],
    url: "https://clearrx.vibed-lab.com/about",
    sameAs: ["https://vibed-lab.com"],
  };

  const breadcrumbLd = {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://clearrx.vibed-lab.com" },
      { "@type": "ListItem", position: 2, name: "About", item: "https://clearrx.vibed-lab.com/about" },
    ],
  };

  return (
    <article className="max-w-2xl mx-auto px-4 py-16 space-y-10">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(personJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbLd) }}
      />

      <header>
        <h1 className="font-serif text-4xl">About ClearRx</h1>
        <p className="mt-4 text-base font-sans" style={{ color: "var(--ink-muted)" }}>
          Built by a pharmacist who got tired of watching patients get buried in FDA label copy.
        </p>
      </header>

      {/* Who I Am */}
      <section className="space-y-4 text-base font-sans leading-relaxed" style={{ color: "var(--ink-muted)" }}>
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>Who I Am</h2>
        <p>
          I&apos;m Jay, a licensed pharmacist with over a decade of clinical experience in retail,
          hospital, and research settings. I specialize in pharmacokinetics and drug-drug
          interactions — specifically how the CYP450 enzyme system affects medication safety.
        </p>
        <p>
          I review medication profiles daily. The most common question I get: &quot;Is it safe to
          take these together?&quot; Existing tools either overwhelm patients with clinical jargon
          or bury the answer under three ad units and a pop-up.
        </p>
        <p>
          My background spans community pharmacy — where I counseled patients face-to-face on their
          medication regimens — to pharmaceutical research, where I studied CYP-mediated metabolism
          and enzyme inhibition profiles at a molecular level. That combination of clinical practice
          and research gives me a perspective that most drug interaction databases lack: I know what
          matters at the patient&apos;s bedside, not just what the FDA label says.
        </p>
      </section>

      {/* Why I Built ClearRx */}
      <section className="space-y-4 text-base font-sans leading-relaxed" style={{ color: "var(--ink-muted)" }}>
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>Why I Built ClearRx</h2>
        <p>
          ClearRx is my answer to that problem. It&apos;s a tool I would actually hand to a patient.
          Clean, fast, private. No account. No data sent anywhere. Results in plain English,
          reviewed by a pharmacist — not generated by an algorithm with no accountability.
        </p>
        <p>
          Every interaction explanation on this site was written or reviewed by me. I stand
          behind every word. When I write that sertraline and tramadol carry a serotonin syndrome
          risk, that&apos;s not copied from a database — it&apos;s drawn from cases I have reviewed
          and clinical guidelines I reference daily.
        </p>
      </section>

      {/* How ClearRx Works */}
      <section className="space-y-4 text-base font-sans leading-relaxed" style={{ color: "var(--ink-muted)" }}>
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>How ClearRx Works</h2>
        <p>
          ClearRx checks your medications against a curated database of clinically significant
          drug interactions. Unlike clinical tools designed for pharmacists, every result includes
          a plain-English explanation of <em>why</em> the interaction matters, <em>what</em> could
          happen, and <em>when</em> to talk to your healthcare provider.
        </p>
        <p>
          The Interaction Map visualizes your entire medication regimen as a network diagram — each
          drug is a node, each interaction is a colored line between them. Red means serious. Yellow
          means moderate. Green means safe. For the first time, you can see your complete medication
          picture at a glance.
        </p>
        <p>
          All processing happens locally in your browser. Your medication list never leaves your
          device. There is no server, no database storing your data, no tracking of what you search.
        </p>
      </section>

      {/* Credentials */}
      <div
        className="p-5 border text-sm font-sans"
        style={{ borderColor: "var(--border)", background: "var(--rx-accent-light)" }}
      >
        <p className="font-mono text-xs uppercase mb-3" style={{ color: "var(--rx-accent)" }}>
          Credentials &amp; Expertise
        </p>
        <ul className="space-y-2 list-disc list-inside" style={{ color: "var(--ink-muted)" }}>
          <li><strong>PharmD</strong> — Doctor of Pharmacy, Licensed Pharmacist</li>
          <li><strong>Senior Pharmaceutical Researcher</strong> — CYP-mediated drug metabolism</li>
          <li><strong>Clinical Pharmacokinetics Specialist</strong> — ADME and drug disposition</li>
          <li><strong>CYP450 Drug Interaction Expert</strong> — enzyme inhibition/induction profiling</li>
          <li><strong>10+ years clinical experience</strong> — retail, hospital, and research settings</li>
        </ul>
      </div>

      {/* Editorial Process */}
      <section className="space-y-4 text-base font-sans leading-relaxed" style={{ color: "var(--ink-muted)" }}>
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>Editorial Process</h2>
        <p>
          Every piece of content on ClearRx follows a structured review process:
        </p>
        <ol className="list-decimal list-inside space-y-2">
          <li>
            <strong>Evidence gathering</strong> — interaction data is cross-referenced against
            FDA drug labels, the Lexicomp database, and published clinical literature.
          </li>
          <li>
            <strong>Clinical translation</strong> — technical mechanisms are translated into
            plain-English explanations without sacrificing accuracy.
          </li>
          <li>
            <strong>Pharmacist review</strong> — every explanation is personally reviewed by me
            for clinical accuracy, appropriate severity classification, and practical relevance.
          </li>
          <li>
            <strong>Regular updates</strong> — the drug database and interaction explanations are
            updated as new safety data, FDA warnings, or clinical guidelines are published.
          </li>
        </ol>
      </section>

      {/* Part of Vibed Lab */}
      <section className="space-y-4 text-base font-sans leading-relaxed" style={{ color: "var(--ink-muted)" }}>
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>Part of Vibed Lab</h2>
        <p>
          ClearRx is part of{" "}
          <a href="https://vibed-lab.com" target="_blank" rel="noopener noreferrer" style={{ color: "var(--rx-accent)" }}>
            Vibed Lab
          </a>
          , a collection of focused, no-frills tools built by Jay. Other projects include:
        </p>
        <div className="space-y-3 mt-4">
          <div className="p-4 border" style={{ borderColor: "var(--border)" }}>
            <a
              href="https://backtest.vibed-lab.com"
              target="_blank"
              rel="noopener noreferrer"
              className="font-serif text-lg"
              style={{ color: "var(--rx-accent)" }}
            >
              CryptoBacktest
            </a>
            <p className="text-sm mt-1">
              Backtest cryptocurrency trading strategies against real historical price data.
            </p>
          </div>
          <div className="p-4 border" style={{ borderColor: "var(--border)" }}>
            <a
              href="https://cycle.vibed-lab.com"
              target="_blank"
              rel="noopener noreferrer"
              className="font-serif text-lg"
              style={{ color: "var(--rx-accent)" }}
            >
              BitcoinCycle Clock
            </a>
            <p className="text-sm mt-1">
              Real-time Bitcoin market cycle positioning with on-chain indicators.
            </p>
          </div>
        </div>
      </section>

      {/* Explore More */}
      <section className="space-y-3">
        <h2 className="font-serif text-2xl" style={{ color: "var(--ink)" }}>Explore ClearRx</h2>
        <div className="flex flex-wrap gap-3 text-sm font-sans">
          <Link
            href="/"
            className="px-4 py-2 border transition-colors hover:border-[var(--rx-accent)]"
            style={{ borderColor: "var(--border)", color: "var(--ink-muted)" }}
          >
            Drug Interaction Checker
          </Link>
          <Link
            href="/learn"
            className="px-4 py-2 border transition-colors hover:border-[var(--rx-accent)]"
            style={{ borderColor: "var(--border)", color: "var(--ink-muted)" }}
          >
            Learning Hub
          </Link>
          <Link
            href="/faq"
            className="px-4 py-2 border transition-colors hover:border-[var(--rx-accent)]"
            style={{ borderColor: "var(--border)", color: "var(--ink-muted)" }}
          >
            FAQ
          </Link>
          <Link
            href="/glossary"
            className="px-4 py-2 border transition-colors hover:border-[var(--rx-accent)]"
            style={{ borderColor: "var(--border)", color: "var(--ink-muted)" }}
          >
            Glossary
          </Link>
          <Link
            href="/contact"
            className="px-4 py-2 border transition-colors hover:border-[var(--rx-accent)]"
            style={{ borderColor: "var(--border)", color: "var(--ink-muted)" }}
          >
            Contact
          </Link>
        </div>
      </section>
    </article>
  );
}
